### ISSUE TITLE
Support bootloader & other boards

### ISSUE THREAD

**Issue by pepijndevos** [nfz/asforth#2]
I was about to write my own AVR Forth when someone linked me to this project.
However, my target is an atmega32u4 with Teensy bootloader.

I browsed through the code, and it seems only one or two files are required to support other boards.
The major part seems to be the interrupt vectors.

I'm just getting started learning assembly, so what I don't quite understand is why the code does not work with a bootloader. Or... **is** this the bootloader?

What are the RAM requirements for this? Some other AVR Forth load code in RAM, limiting your code size. But I'm starting to suspect this project acts as a bootloader burning compiled Forth to the flash.

If there is any way this could run Forth on the Teensy 2.0 bootloader, I'd be happy to try to contribute.

**Comment by nfz** [comment]
Hi Pepijn de Vos,

This project is still in its infancy and only works with atmega328. You are right in that it should only take a few modifications to a couple of files to get it to work on an atmega32u4. Many I/O addresses are different along with the interrupt vector table. SRAM size is bigger so end of ram address would have to be changed.

Asforth core code is built using Gnu As and not the Atmel assembler. The build environment works good on Linux but I have never tried on Windows.

A more mature forth project is AmForth which supports atmega32u4 out of the box: http://amforth.sourceforge.net/
Another forth project for AVR is FlashForth: http://flashforth.com/
AmForth and FlashForth use the Atmel assembler and build on Windows.

Asforth, AmForth, and FlashForth do not use a bootloader. Words are compiled into flash as you write them. About 300 bytes are used by the input buffer, data stack, and return stack. All code is compiled to flash, including the dictionary, and you are only limited by the amount of flash on the chip.

You do require an Atmega ISP programmer to upload the core code into flash initially. You can get an ISP for a few bucks on ebay, amazon, or Aliexpress. They are worthwhile to have and easy to use.

Cheers,
Jeff.

> 
> 
> 
>   
>   
>  
>

**Comment by pepijndevos** [comment]
I'm on a Mac and I do have an ISP, so that is not my problem.
I'm glad to hear that there are AVR Forth projects that work on my chip and compile to flash.
However, the Teensy bootloader is not opensource, so once I wipe it there is no way back.
It's also not so convenient that others using my code *also* have to wipe their bootloader.
But thanks for all the info!

**Comment by nfz** [comment]
When I first started developing asforth I used the arduino bootloader to load the core. This was before I used an ISP. The drawback is that the bootloader is only used to load the forth core and would never get used again unless the core needed a change. This method was used for the initial development of the Forth core. All words defined later are done using the optimized flash write routines in the forth core. Unfortunately the arduino bootloader does not have that capability so I got rid of it since it was wasting flash. I don't know what the features of the Teensy bootloader are. If the Teensy bootloader size is small then maybe you don't need to get rid of it and its a failsafe backup if the forth core gets trashed (it does happen).

> 
> 
> 
>   
>   
>  
>

**Comment by pepijndevos** [comment]
Ah, I think I get it now. The SPM instruction only functions form the bootloader section [1], so the only way to write to the flash is to put the core inside the bootloader, unless the bootloader exposes an API for writing to flash [2].

[1]: http://www.atmel.com/Images/doc2575.pdf
[2]: http://amforth.sourceforge.net/faq.html#what-about-boot-loaders

**Comment by nfz** [comment]
Yes, you got it.

If there is room in the boot loader section you can use avrdude to write the !i word in the space available. It is tedious to setup the first time since you are dealing with hard coded addresses that need to be setup in the assembler source. !i is short enough that I used avrdude in terminal mode to write each hex code individually the first time to see if it would work. Not something you want to do every day.

You may not have the Teensy bootloader source but you can use avrdude to explore the bootloader section of flash to find space. Areas that are available will be 0xFFFF. Note: the fuses will have to be changed in order to write to the bootloader section of Flash.

Warning: Backup the bootloader section using avrdude before you start changing things. If things go wrong you can reflash the bootloader using the backup.

If you are going to be using forth for just your self then this is a good learning experience. If you want others to be able to load your code on their boards then this is not the avenue to take.

> 
> 
> 
>   
>   
>  
>

**Comment by pepijndevos** [comment]
Haha, would it not be easier to contribute a flash writing API to the Arduino bootloader?
I tried to find out how to "link" to a function in the bootloader, but so far unsuccessful.
Calculate and hardcode the address it seems.

Meanwhile I started learning AVR assembly by hand-coding a simple Forth program: https://gist.github.com/anonymous/8739207f7222cf052410
I might make an AOT compiled Forth that you can just upload to an Arduino bootloader with avrdude.

**Comment by nfz** [comment]
That is basically how this project started. I made small simple hand coded Forth like assembly programs to see how they worked and the core grew from there. I am using amforth and flashforth as references/inspiration. Making lots of mistakes along the way but I find its a good way to learn.
